#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10


#define BROCESSOROS_TOTAL_INTERRUPTS 512

// 100MB heap size
#define BROCESSOROS_HEAP_SIZE_BYTES 104857600
#define BROCESSOROS_HEAP_BLOCK_SIZE 4096
#define BROCESSOROS_HEAP_ADDRESS 0x01000000 
#define BROCESSOROS_HEAP_TABLE_ADDRESS 0x00007E00

#define BROCESSOROS_SECTOR_SIZE 512

#define BROCESSOROS_MAX_FILESYSTEMS 12
#define BROCESSOROS_MAX_FILE_DESCRIPTORS 512

#define BROCESSOROS_MAX_PATH 108
#define BROCESSOROS_TOTAL_GDT_SEGMENTS 6

#define BROCESSOROS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define BROCESSOROS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define BROCESSOROS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define BROCESSOROS_PROGRAM_VIRTUAL_STACK_ADDRESS_END BROCESSOROS_PROGRAM_VIRTUAL_ADDRESS_START -BROCESSOROS_USER_PROGRAM_STACK_SIZE

#define BROCESSOROS_MAX_PROGRAM_ALLOCATIONS 1024
#define BROCESSOROS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif
